import "./globals.css";

import { GeistSans } from "geist/font/sans";
// import { GeistMono } from "geist/font/mono";
// GeistMono: --font-geist-mono
// font-family: var(--font-geist-mono) as an example

import Script from "next/script";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { ThemeProvider } from "@/util/contexts/theme/server";
import { getServerTheme } from "@/util/helpers/getServerTheme";

export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }]
};

export default function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={getServerTheme()} suppressHydrationWarning>
            <head>
                <script src="/theme.js" type="text/javascript" />
                <Script src="/serverRender.js" strategy="beforeInteractive" />
            </head>
            <body className={`${GeistSans.className} bg-white dark:bg-black`}>
                <ThemeProvider>
                    <Header />
                    {children}
                    <Footer />
                </ThemeProvider>
            </body>
        </html>
    );
}
